version: '3.1'

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - {{cookiecutter.project_name}}-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  {{cookiecutter.project_name}}-local:
    container_name: {{cookiecutter.project_name}}-local
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: {{cookiecutter.project_name}}-local
    build: ./
    command: >
      bash -c "python wait_for_postgres.py && ./manage.py collectstatic --no-input --clear &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./:/code
  {{cookiecutter.project_name}}:
    container_name: {{cookiecutter.project_name}}
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: {{cookiecutter.project_name}}
    build: ./
    command: >
      bash -c "python wait_for_postgres.py && ./manage.py collectstatic --no-input --clear &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  {{cookiecutter.project_name}}-postgres: